### ISSUE TITLE
Lage nextjs app router inngangspunkt i nav-dekoratoren-moduler

### ISSUE THREAD

**Issue by max-nav** [navikt/nav-dekoratoren#138]
- Lage en tilsvarende funksjon slik som injectDecoratorServerside, men for det nye approuter endepunktet. 

Anders har lagt til decorator-next som et environment i moduler pakken, så det er mulig å teste den nye. 
må bruke denne versjonen: 2.1.4-beta.2

```ts
injectDecoratorServerSide({
        params: {
         ...
        },
        {
        env: 'devNext'
        },
})

```

repo: https://github.com/navikt/nav-dekoratoren-moduler#server-side-rendering-anbefalt

**Comment by max-nav** [comment]
@karl-run Jeg tenkte kanskje at du ville ha æren av å gjøre dette?

**Comment by talepre** [comment]
Sendt melding til @karl-run for å høre om denne kan lukkes

**Comment by talepre** [comment]
Tilbakemelding fra @karl-run om at dette fungerer og kan lukkes
