### ISSUE TITLE
UU: Størrre klikkflate på lenker

### ISSUE THREAD

**Issue by PerOlavM** [navikt/nav-dekoratoren#374]
Oppnå minimum 44 x 44px på alle klikkflater.
* Brødsmulesti: kan oppnås ved å sette padding-block i lenker til 6px
* Språkvelger: kan oppnås ved å sette padding-block i button til 10px
* Lenkeliste footer: kan oppnås ved å sette padding-block i lenker til 10px

Husk også simple-header og -footer

**Comment by andnorda** [comment]
Done
