### ISSUE TITLE
Innhold i menyen lastes ikke inn på 404-side

### ISSUE THREAD

**Issue by macbruker** [navikt/nav-dekoratoren#429]
Det ser ut som noe er galt med innhenting av menyen på 404-sider. Kanskje en verdi som forventes, men som ikke finnes på de sidene?
![image](https://github.com/user-attachments/assets/ea690c08-8b81-4998-ae0d-1059e0ecfba6)

Dette er feilmeldingene jeg ser i devtools:
![image](https://github.com/user-attachments/assets/87f81847-f5e3-4f92-8185-82101115cf23)

**Comment by anders-nom** [comment]
Er ganske sikker på at dette skyldtes en feil i version-skew funksjonaliteten vår, som førte til feil-response på requester fra utdaterte klient-versjoner. 404-siden til XP-frontend'en er en statisk side som kun rendres build-time, så feilen ville nok oppstå der i tidsrommet mellom en ny dekoratør-deploy og ny frontend-deploy.

Feilen skal være fikset nå.
