### ISSUE TITLE
Header og footer vises ikke på søkeresultatside med filter

### ISSUE THREAD

**Issue by ojnybo** [navikt/nav-dekoratoren#430]
Dersom man går til søkeresultatsiden, velger filter og trykker "oppdater" forsvinner header og footer.
Gjelder også hvis man går til direktelenke til søkeresultatside med filtervalg.

Eksempel: https://www.nav.no/sok?ord=&page=0&f=analyser-og-forskning&uf=nyheter&s=1&preferredLanguage=nb

Får 500-feil mot: 
https://www.nav.no/dekoratoren/env?chatbot=true&breadcrumbs=%5B%7B%22title%22%3A%22S%C3%B8k%22%2C%22url%22%3A%22%2Fsok%22%7D%5D&context=innhold-fra-fylker

I tillegg til SyntaxError i konsollet.

Ble oppdaget i Siteimprove: https://my2.siteimprove.com/Accessibility/1002489/NextGen/Issue/1?pageSegments=&issueKind=1&ruleId=87&exceptTags=&includingTags=&tagFilterType=2

**Comment by ojnybo** [comment]
Fra @terjeofnorway :det er søkefrontenden. Jeg tror jeg vet hvor feilen ligger. Fikser om litt!

Dvs, søkefrontenden forsøker å send inn ugyldig context slik som “presse”, “statistikk” etc til dekortøren. Slik det nå er den kodet til å feile hvis andre ting enn “privatperson”, “arbeidsgiver” eller “samarbeidspartner” sendes inn som kontekst.

**Comment by ojnybo** [comment]
I første omgang defaulter vi disse til privatperson-kontekst, på sikt kan man se på muligheten for å huske hvilken kontekst man kom fra

**Comment by terjeofnorway** [comment]
@ojnybo Denne er vel fikset nå. Siste kommentar om mulighet for å huske kontekst i større grad på tvers av applikasjoner bør vi kanskje ha som egen oppgave? Jeg setter denne til ferdig ihvertfall.
