### ISSUE TITLE
Håndtere endring av innlogget bruker innen samme sesjon

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-dekoratoren#432]
Dersom innlogget bruker endres underveis i en sesjon, bør vi håndtere det på et vis slik at data fra forrige bruker ikke lengre vises til eller påvirker ny bruker.

Eksempel:
- Bruker 1 logger inn, begynner å fylle ut en søknad, og tar en pause.
- Bruker 2 åpner en ny tab på samme maskin, logger ut, og logger inn på egen bruker.
- Bruker 1 kommer tilbake til samme maskin, åpner "sin" tab (som tilsynelatende fortsatt er logget inn som bruker 1).
- Bruker 1 gjør ferdig søknaden og sender inn. Ettersom det nå egentlig er bruker 2 som er innlogget, vil denne nå enten feile eller sendes inn for bruker 2 (avhengig av validering i søknaden).

Vi kan f.eks. vise en modal i tabber med "feil" bruker-sesjon, som tvinger brukeren til å logge inn på nytt for å kunne fortsette.

Sikkert flere måte dette kan løses på teknisk for å kommunisere innlogget bruker mellom tabber. [Broadcast Channel](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) er et mulig valg, men dette fungerer kun på same-origin (ikke mellom sub-domener). PostMessage kan kanskje brukes? Evt. kalle auth ved window focus?

**Comment by taniaholst** [comment]
Internflatedekoratøren har gjort det på denne måten: https://github.com/navikt/internarbeidsflatedecorator/blob/master/packages/internarbeidsflate-decorator-v3/src/components/modals/NewUserModal.tsx

...men usikker på om det kan brukes mtp sub-domener
