### ISSUE TITLE
uu-bug: åpne menyer fanger ikke fokus

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/nav-dekoratoren#453]
Når dropdown-menyene er åpne, ser de ut som om de skal være modale (dvs. blokker for andre innhold), men det er de ikke.  Når et dekkende lag vises, skal det ikke være mulig å flytte tastatur- eller skjermleserfokus bak det. Det bør også gå an å lukke menyen med Esc.

![Skjermbilde som viser fokus bak menyens dekkende lag](https://github.com/user-attachments/assets/5fdc7254-23aa-427c-9a1c-41b28f42b892)

Som det er satt opp nå, bryter alle nettsider som bruker dekoratøren flere WCAG-krav.

**Comment by anders-nom** [comment]
Regresjon etter omskrivningen av dekoratøren som ble prodsatt i juli.

Fort gjort å fikse, må bare legge på noen event listeners for focus og escape i DropdownMenu-komponenten.
