### ISSUE TITLE
Arc Toolkit melder error i dekoratøren

### ISSUE THREAD

**Issue by amundsor** [navikt/nav-dekoratoren#476]
Vi holder på med Tilgjengelighetserklæringen, og Arc Toolkit melder om følgende feil i dekoratøren:
![image](https://github.com/user-attachments/assets/8d5f15a5-aa17-4d7a-8fd1-09eb0039cb2f)
![image](https://github.com/user-attachments/assets/f5a01b50-70f0-4928-bb77-1a213d47840c)
![image](https://github.com/user-attachments/assets/ad046644-7d42-4c83-b784-c00ce3590f92)
![image](https://github.com/user-attachments/assets/d6b72e06-5b22-4771-97b5-4e0eeffc2099)

**Comment by ojnybo** [comment]
Dette er falske positive fra ARC sin side.
Den liker ikke at vi bruker custom html-elementer i den nye dekoratøren. Dette er helt vanlig i dag, og ingen moderne nettlesere har problemer med dette. Siteimprove reagerer ikke på dette.
Når det gjelder missing alt, så er det teknisk korrekt, men det er for å unngå dobbelt opplesning av "Logg inn" i skjermlesere.
Igjen, ingen andre verktøy enn ARC reagerer på dette. ARC er ikke smart nok til å skjønne at det er OK.
